version: '3.8'

services:
  orca-core-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      - ORCA_MODE=RULES_PLUS_AI
      - ORCA_USE_XGB=true
      - ORCA_EXPLAIN_ENABLED=true
      - ORCA_MODEL_DIR=/app/models/xgb
      - ENVIRONMENT=development
      - PYTHONPATH=/app/src
    volumes:
      # Mount local models directory for development
      - ./models:/app/models:ro
      # Mount local .env.local for development secrets
      - ./.env.local:/app/.env.local:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - orca-network

  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orca-core-api
    networks:
      - orca-network
    profiles:
      - production

networks:
  orca-network:
    driver: bridge

volumes:
  models:
    driver: local


