apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orca-keyvault-secrets
  namespace: orca-core
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""  # Will be set by the managed identity
    keyvaultName: "orca-keyvault-staging"
    tenantId: "924408c9-dc6b-492e-b81d-329a364ac1ef"
    objects: |
      array:
        - |
          objectName: azure-openai-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: azure-openai-endpoint
          objectType: secret
          objectVersion: ""
        - |
          objectName: azure-openai-deployment
          objectType: secret
          objectVersion: ""
        - |
          objectName: orca-decision-mode
          objectType: secret
          objectVersion: ""
        - |
          objectName: orca-use-xgb
          objectType: secret
          objectVersion: ""
        - |
          objectName: orca-explain-enabled
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: orca-secrets
      type: Opaque
      data:
        - objectName: azure-openai-api-key
          key: AZURE_OPENAI_API_KEY
        - objectName: azure-openai-endpoint
          key: AZURE_OPENAI_ENDPOINT
        - objectName: azure-openai-deployment
          key: AZURE_OPENAI_DEPLOYMENT
        - objectName: orca-decision-mode
          key: ORCA_DECISION_MODE
        - objectName: orca-use-xgb
          key: ORCA_USE_XGB
        - objectName: orca-explain-enabled
          key: ORCA_EXPLAIN_ENABLED
