name: CI
on:
  pull_request:
  push: { branches: [main] }
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv python install 3.12
      - run: uv sync --all-extras --dev
      - run: uv run ruff check .
      - run: uv run black --check .
      - run: uv run mypy src
      - run: uv run pytest -q --maxfail=1 --disable-warnings
